spring.config.import=configserver:

spring.application.name=auth-service-test

# Disable external services during tests
spring.cloud.config.enabled=false

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.auto-startup=false

# Fake Keycloak values for tests
keycloak.server-url=http://localhost:8080
keycloak.realm=test-realm
keycloak.client-id=test-client
keycloak.admin-user=admin
keycloak.admin-password=admin
keycloak.client-secret=test-secret

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/test-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test-realm

management.endpoints.web.exposure.include=health,info